// analytics.service.ts
// ── Kisho Admin — Analytics API Service ────────────────────────────────────
import { Injectable } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { Observable } from 'rxjs';

// ── Response Interfaces ───────────────────────────────────────────────────────

export interface TopProduct {
  id:            string;
  title:         string;
  totalSold:     number;
  totalRevenue:  number;          // revenue generated by THIS product alone
  basePrice:     number;
  discountPrice: number;
  thumbnail:     string | null;
  category:      string;
}

export interface OrderMetrics {
  total:      number;
  pending:    number;
  confirmed:  number;
  processing: number;
  shipped:    number;
  delivered:  number;
  cancelled:  number;
  refunded:   number;
}

export interface Financials {
  grossRevenue:   number;   // all active-order revenue
  pendingRevenue: number;   // revenue locked in pending orders
  netProfit:      number;   // estimated 35% margin
  activeOrders:   number;   // orders that contributed to gross
}

export interface AnalyticsSummary {
  financials: Financials;
  topProduct: TopProduct | null;
  metrics:    OrderMetrics;
}

export interface AnalyticsSummaryResponse {
  success: boolean;
  data:    AnalyticsSummary;
}

// ── Service ───────────────────────────────────────────────────────────────────

@Injectable({ providedIn: 'root' })
export class AnalyticsService {
  private readonly endpoint = '/api/admin/analytics/summary';

  constructor(private readonly http: HttpClient) {}

  getSummary(): Observable<AnalyticsSummaryResponse> {
    return this.http.get<AnalyticsSummaryResponse>(this.endpoint, {
      withCredentials: true,
    });
  }
}
